# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QnuBIBO42-t2dWxES1Rj5hK_CZcCW_y
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def leibniz_pi(n):
    return 4 * sum((-1)**k / (2*k + 1) for k in range(n))

true_pi = np.pi
N_values = [10, 100, 1000, 10000]
errors_abs = []
errors_rel = []

# Calcular errores
for N in N_values:
    approx_pi = leibniz_pi(N)
    error_abs = abs(true_pi - approx_pi)
    error_rel = error_abs / true_pi
    errors_abs.append(error_abs)
    errors_rel.append(error_rel)
    print(f"N={N}: Error absoluto={error_abs}, Error relativo={error_rel}")

# Guardar resultados en un DataFrame de pandas
df = pd.DataFrame({
    'N': N_values,
    'Error Absoluto': errors_abs,
    'Error Relativo': errors_rel
})

# Guardar DataFrame en un archivo Excel
df.to_excel('errores_pi.xlsx', index=False)

# Graficar resultados
plt.figure()
plt.plot(N_values, errors_abs, label='Error absoluto', marker='o')
plt.plot(N_values, errors_rel, label='Error relativo', marker='s')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('N')
plt.ylabel('Error')
plt.legend()
plt.title('Errores en la aproximación de pi')
plt.show()